Sahyog/urls.py
from django.contrib import admin
from django.urls import path, include
from user_accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_accounts/', include('user_accounts.urls')),
    path('proposals/', include(('proposals.urls', 'proposals'), namespace='proposals')),
    path('',views.index,name='index'),
]

proposals/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('home/', views.post_list, name='post_list'),
    path('new/', views.post_create, name='post_new'),
    path('edit/<int:pk>/', views.post_update, name='post_edit'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('index/', include(('user_accounts.urls', 'user_accounts'), namespace='index')),
    path("by/join/<int:pk>/",views.SingleGroup.as_view(),name="post_join"),
    path("join/<int:pk>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<int:pk>/",views.LeaveGroup.as_view(),name="leave"),
    path("userpost/",views.UserPosts.as_view(),name="for_user"),

]

proposals/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class blog_posts(models.Model):
    Initiative_Title = models.CharField(max_length=255, unique = True)
    requirements = models.CharField(max_length=40000, default= " ")
    name = models.CharField(max_length=100)
    budget = models.PositiveIntegerField(default = 0)
    location = models.CharField(max_length=100, default = "")
    attendees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='attending', blank=True)
    num_of_attendees = models.PositiveIntegerField(default=0, blank=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.title

    def get_post_url(self):
        return reverse('post_edit', kwargs={'pk': self.pk})

proposals/forms.py
from django import forms
from .models import blog_posts


class PostsForm(forms.ModelForm):
    name = forms.CharField(disabled=True)

    class Meta:
        model = blog_posts
        fields = ['id', 'Initiative_Title','requirements','name','location', 'budget','attendees']

proposals/views.py
# Inbuilt system imports
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.views import generic
# User created Imports
from .forms import PostsForm
from .models import blog_posts
# Check requirements.txt for this feature
from braces.views import SelectRelatedMixin


# Create your views here.

# Listing the proposals
def post_list(request, template_name='proposals/post_list.html'):
    posts = blog_posts.objects.all()
    data = {}
    data['object_list'] = posts
    return render(request, template_name, data)


# Creating a proposal only by a company
def post_create(request, template_name='proposals/post_form.html'):
    a=User.objects.get(username=request.user.username)
    form = PostsForm(request.POST or None,initial={'name':a})
    if form.is_valid():
        form.save()
        return redirect('proposals:post_list')
    return render(request, template_name, {'form': form})

# Changing the details of a proposal
def post_update(request, pk, template_name='proposals/post_form.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    form = PostsForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('proposals:post_list')
    return render(request, template_name, {'form': form})

# Deleting a proposal
def post_delete(request, pk, template_name='proposals/post_delete.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    if request.method=='POST':
        post.delete()
        return redirect('proposals:post_list')
    return render(request, template_name, {'object': post})


# Joining or leaving an event
class SingleGroup(generic.DetailView):
    model = blog_posts
    template_name = 'proposals/post_join.html'

# Displaying usser posts
class UserPosts(generic.ListView):
    model = blog_posts
    select_related = ('user')
    template_name = "proposals/user_post_list.html"
    def get_queryset(self):
        try:
            self.post_list = blog_posts.objects.all()
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_list"] = self.post_list
        return context

# Adding user to the list of attendees
class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("proposals:post_join",kwargs={'pk':self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(blog_posts,pk=self.kwargs.get('pk'))
        attendee = User.objects.get(username=request.user)

        try:
            group.attendees.add(attendee)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.Initiative_Title)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.Initiative_Title))

        return super().get(request, *args, **kwargs)

# Removing user from the list of attendees
class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("proposals:post_join",kwargs={'pk':self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(blog_posts,pk=self.kwargs.get('pk'))
        attendee = User.objects.get(username=request.user)
        try:
            group.attendees.remove(attendee)
        except:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )

        else:
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)
        
        

proposals/templates/proposals/post_base.html
{% extends 'user_accounts/base.html' %}
{% block content %}
<div class="container">
	{% block pre_post %}{% endblock %}
	{% block post_content %}{% endblock %}
	{% block post_post %}{% endblock %}
</div>
{% endblock %}

proposals/templates/proposals/post_delete.html
{% extends 'proposals/post_base.html' %}

{% block title %}Delete Event - Sahyog{%  endblock %}

{% block pre_post %}
  <div class="container">
    <form method="post">{% csrf_token %}
      <br>
      <p style="font-family: Bitter; font-size: x-large;">Are you sure you want to delete "{{ object }}" ?</p><br>
      <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
    </form>
  </div>
{% endblock %}

proposals/templates/proposals/post_form.html
{% extends 'proposals/post_base.html' %}
{% block title %}Create an Event - Sahyog{% endblock %}
{% block post_content %}
	<div class="container">
		<br>
		<form method="POST" id="postForm">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
			</div>
			<input type="submit" name="" value="Post" class="btn btn-primary btn-lg">
		</form>
	</div>
{% endblock %}

proposals/templates/proposals/post_join.html
{% extends 'proposals/post_base.html' %}
{% block title %}Details of the Proposal - Sahyog{% endblock %}
{% block post_content %}
	<div class="container">
		<p style="font-family: Bitter; font-size: x-large;">Post ID: {{ blog_posts.id}}</p>
		<p style="font-family: Bitter; font-size: x-large;">Initiative Title: {{ blog_posts.Initiative_Title}}</p>
		<p style="font-family: Bitter; font-size: x-large;">Budget: {{ blog_posts.budget}}</p>
		<p style="font-family: Bitter; font-size: x-large;">Requirements: {{ blog_posts.requirements}}</p>
		{% if user in blog_posts.attendees.all %}
			<a class="btn btn-danger btn active w-25" href="{% url 'proposals:leave' pk=blog_posts.pk %}">Leave</a>
		{% else %}
			<a class="btn btn-success btn active w-25" href="{% url 'proposals:join' pk=blog_posts.pk %}">Join</a>
		{% endif %}
	</div>
{% endblock %}

proposals/templates/proposals/post_list.html
{% extends 'proposals/post_base.html' %}
{% block title %}Proposals List - Sahyog{% endblock %}
{% block post_content %}
  <div class="container">
    <h1 style="font-family: Amaranth;"> Post List!</h1>
    
    {% for post in object_list %}
      <br>
      <div class="media border p-3">
        <div class="media-body">
          <p  style="text-decoration: none; font-size: x-large;display: inline;" class="text-body">{{ post.Initiative_Title }}</p> &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;
          <a href="{% url 'proposals:post_join' post.id %}" class="btn btn-success btn active w-25" style="display: inline;">View Event Details</a>
          {% if post.name == user.username %}<br><br>
            <a href="{% url 'proposals:post_edit' post.id %}" class="btn btn-info btn-sm">Edit</a>
            <a href="{% url 'proposals:post_delete' post.id %}" class="btn btn-info btn-sm">Delete</a>
          {% endif %}
          <br>
        </div>
      </div>
    {% endfor %}
    <p>{{ UserProfile.retcat }}</p>
    {% if UserProfile.retcat == 'company' %}
      <a href="{% url 'proposals:post_new' %}">New Proposal</a>
      <br>
    {% endif %}
  </div>
{% endblock %}

proposals/templates/proposals/user_post_list.html
{% extends 'proposals/post_base.html' %}

{% block title %}Your Post - Sahyog{% endblock %}

{% block pre_post %}
<div class="col-md-4">
  <h1 style="font-family: Amaranth;">Post History</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
  <br>
  {% for post in post_list %}
  <br>
  {% if post.name == user.username %}
    <div class="media border p-3">
          <div class="media-body">
            <li>
              <a href="{% url 'proposals:post_join' post.id %}" style="text-decoration: none; font-size: x-large;" class="text-body">{{ post.Initiative_Title }}</a> &nbsp; &nbsp;
                <a href="{% url 'proposals:post_edit' post.id %}" class="btn btn-info btn-sm">Edit</a>
                <a href="{% url 'proposals:post_delete' post.id %}" class="btn btn-info btn-sm">Delete</a>
              <br>
               <br>
            </li>
          </div>
        </div>
          
  {% endif %}
  {% endfor %}
</div>
{% endblock %}