Sahyog/urls.py
from django.contrib import admin
from django.urls import path, include
from user_accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_accounts/', include('user_accounts.urls')),
    path('proposals/', include(('proposals.urls', 'proposals'), namespace='proposals')),
    path('',views.index,name='index'),
]

proposals/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('home/', views.post_list, name='post_list'),
    path('new/', views.post_create, name='post_new'),
    path('edit/<int:pk>/', views.post_update, name='post_edit'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('index/', include(('user_accounts.urls', 'user_accounts'), namespace='index')),
    path("by/join/<int:pk>/",views.SingleGroup.as_view(),name="post_join"),
    path("join/<int:pk>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<int:pk>/",views.LeaveGroup.as_view(),name="leave"),
    path("userpost/",views.UserPosts.as_view(),name="for_user"),

]

user_accounts/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='user_login'),
    path('complogin/', views.comp_login, name='user_login'),

]

user_accounts/models.py
from django.db import models

from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    INDIVIDUAL = 'Individual'
    COMPANY = 'Company'
    CHOICES = (
        (INDIVIDUAL, 'Individual'), 
        (COMPANY, 'Company'),
        )
    category= models.CharField(max_length=100,choices=CHOICES,default='Individual')
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

user_accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('address','category')

user_accounts/views.py
# System imports
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# User defined imports
from .models import UserProfile
from .forms import UserForm, UserProfileInfoForm

# Create your views here.

# Home page at localhost:8000
def index(request):
    return render(request,'user_accounts/index.html')

# Just for show -- Note to Prarthna : "Remove it if not needed"
@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

# Registering a user - Company or Individual
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'user_accounts/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

# Individual login view
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        x = User.objects.get(username=username)
        y = UserProfile.objects.get(user=x)
        print(y.address)
        h=y.address


        user = authenticate(username=username, password=password,)
        if user:
            if user.is_active :
                if  y.category=='Individual':
                    login(request,user)
                else:
                    return HttpResponse("not valid.")
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'user_accounts/login.html', {})


# Company Login view
def comp_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        x = User.objects.get(username=username)
        y = UserProfile.objects.get(user=x)
        print(y.address)
        h=y.address


        user = authenticate(username=username, password=password,)

        if user:
            if user.is_active :
                if  y.category=='company':
                    login(request,user)
                else:
                    return HttpResponse("not valid.")

                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'user_accounts/complogin.html', {})

user_accounts/templates/user_accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static './user_accounts/css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amaranth:400,700|Carter+One|Courgette|Cuprum:400,700|Fugaz+One|Merienda:400,700|Oleo+Script:400,700|Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bitter|Coiny|Josefin+Sans|Libre+Baskerville|Merriweather" rel="stylesheet">
  </head>
  <body style="background-image: url(http://www.manjeetgroup.com/images/csr.jpg); background-repeat: no-repeat; background-size: cover">
    <div class="container e55" style="background-color: white;padding-left: 0px;padding-right: 0px;">
      <div class="clearfix">
        <blockquote class="blockquote" align="center">
          <h1 class="e90 display-3">Sahyog</h1>
        <footer class="blockquote-footer" style="margin-top: 2px;">Together we grow</footer>
      </blockquote>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark"
      style="background-color: #000066">
      <a href="#" class="navbar-brand"><img class="img-fluid float-left e7" src="{% static './user_accounts/img/logo.png' %}"></a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarcon" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarcon">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item text-white">
            <a href="{% url 'index' %}" class="nav-link text-white">Home</a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link text-white">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'logout' %}" class="nav-link text-white">Logout</a>
          </li>
          <li class="nav-item float-right">
            <a href="{% url 'proposals:post_join' user.id %}" class="nav-link text-white">Create Proposal</a>
          </li>
          <li class="nav-item float-right">
              <a href="{% url 'proposals:post_list' %}" class="nav-link text-white">All proposals</a>
            </li>
          <li class="nav-item"><a href="{% url 'proposals:for_user' %}" class="nav-link text-white">Your Proposals</a></li>
        <li class="nav-item"><a href="/user_accounts/user_profile/" class="nav-link text-white">Your Profile</a></li>
    
          {% else %}
          <li><a href="/user_accounts/register/" class="nav-link text-white">Register</a></li>
          <li class="nav-item dropdown">
            <a href="" class="nav-link dropdown-toggle text-white" id="navbardrop" data-toggle="dropdown">Login</a>
            <div class="dropdown-menu">
              <a href="/user_accounts/login/" class="dropdown-item">Login for Individual</a>
              <a href="/user_accounts/complogin/" class="dropdown-item">Login for Company</a>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <br>
    <div class="container-fluid foo">
      <footer>
        <div class="e73 container-fluid">
          <h6><small><strong>Sahyog</strong></small></h6>
          <h4 align="center">USEFUL LINKS<hr width=500px class="style"></h4>
          <ul class="nav nav-pills nav-justified">
            <li class="nav-item">
              <a class="nav-link text-white e26 " href="{% url 'index' %}">HOME</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white e26" href="">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white e26" href="">CONTACT US</a>
            </li>
          </ul><br>
        </div>
        <p align="center">Copyright &copy; Sahyog. All Rights Reserved </p>
      </div>
    </footer>
  </div>
</div>
</body>
</html>

user_accounts/templates/user_accounts/carousel.html
<div class="carousel slide" id="demo" data-ride="carousel">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
        </ul>

    <!-- The slideshow -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="a12" src="https://image.shutterstock.com/image-vector/csr-concept-illustration-idea-responsibility-260nw-1085306945.jpg">
        </div>
        <div class="carousel-item">
            <img class="a12" src="https://www.researchgate.net/profile/Murad_Al-Nashmi2/publication/303975125/figure/fig1/AS:455436529868800@1485595938619/Corporate-Social-Responsibility-CSR.png">
        </div>
        <div class="carousel-item">
            <img class="a12" src="https://www.mahindracomviva.com/wp-content/uploads/2017/03/1459942542-csr-home.jpg">
        </div>
    </div>

    <!-- Left and Right Controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div><br>
<h1 class="e25">Welcome To Sahyog</h1>
<pre class="e24">Welcome to the official website of Sahyog, New Delhi. This one facet of ours which is 100% selfless. 
    To the extent that we like to get our hands down and dirty when it comes to making a 
    difference in the lives of underprivileged. You will find yourself 
 sitting next to the child that we intend to support, guiding him with love, knowledge and concern. 
  Pure genuine responsbility is what we are proud of, and we would like to share it with you.
</pre>

user_accounts/templates/user_accounts/complogin.html
{% extends 'user_accounts/base.html' %}

{% block title %}Login - Sahyog{% endblock %}

{% block content %}
	<div class="container">
		<div class="align-content-center" align="center">
			<br>
			<div style="border: 1px solid black; width: 600px; height: 300px;">
				<h1 style="font-family: "Ubuntu">Login here :</h1>
				<br>
				<form method="post" >
					{% csrf_token %}
					{# A more "HTML" way of creating the login form#}
					<div class="form-group" align="center">
						<label for="username">Username:</label>
						<input type="text" name="username" placeholder="Username" id="username">
					</div>
					<div class="form-group" align="center">
						<label for="password">Password:</label>
						<input type="password" name="password" placeholder="Password" id=password>
					</div>
					<div class="form-check">
						<label class="form-check-label" for="radio1">
							<input type="radio" class="form-check-input" id="radio1" name="optradio" value="option1" checked>Company
						</label>
					</div><br>
					<input type="submit" name="" value="Login" class="btn btn-primary btn-lg">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

user_accounts/templates/user_accounts/index.html
{% extends "user_accounts/base.html" %}

{% block title %}Sahyog - A CSR Portal for all{% endblock %}

{% block content %}
    <br>
    <div class="container">
        {% include 'user_accounts/carousel.html' %}
    </div>
{% endblock %}

user_accounts/templates/user_accounts/login.html
{% extends 'user_accounts/base.html' %}

{% block title %}Login - Sahyog{% endblock %}

{% block content %}
	<div class="container">
		<div class="align-content-center" align="center">
			<br>
			<div style="border: 1px solid black; width: 600px; height: 300px;">
				<h1 style="font-family: "Ubuntu">Login here :</h1>
				<form method="post" >
					{% csrf_token %}
					{# A more "HTML" way of creating the login form#}
					<div class="form-group">
						<label for="username">Username:</label>
						<input type="text" name="username" placeholder="Username" id="username">
					</div>
					<div class="form-group">
						<label for="password">Password:</label>
						<input type="password" name="password" placeholder="Password" id=password>
					</div>
					<div class="form-check">
						<label class="form-check-label" for="radio1">
							<input type="radio" class="form-check-input" id="radio1" name="optradio" value="option1" checked>Individual
						</label>
					</div><br>
					<input type="submit" name="" value="Login" class="btn btn-primary btn-lg">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

user_accounts/templates/user_accounts/profile_update.html
{% extends "user_accounts/base.html" %}
{% block content %}

<p>Username(unchangeable) : {{ user.username }}</p>
<form method="POST" id="UserProfile_form">
  <div class="form-group">
  {% csrf_token %}
  {{ form.as_p }}
</div>
  <input type="submit" name="" value="Update" class="btn btn-primary">
</form>
{% endblock %}

user_accounts/templates/user_accounts/registration.html
{% extends "user_accounts/base.html" %}

{% block title %}Register - Sahyog{% endblock %}

{% load staticfiles %}
{% block content %}
  <br>
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          <div class="form-group">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register" class="btn btn-primary btn-lg">
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

user_accounts/templates/user_accounts/signup.html
{% extends "user_accounts/base.html" %}

{% block title %}Register - Sahyog{% endblock %}

{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

user_accounts/templates/user_accounts/user_profile.html
{% extends "user_accounts/base.html" %}
{% load staticfiles %}
{% block content %}
<br>
  <div class="container">
    <div class="jumbotron">
        <h1 style="font-family: Amaranth;"> Profile</h1>
        {% for person in people_list %}
            {% if user == person.user %}
                <p>User Name: {{ person.user }}</p>
                <p>Address : {{ person.address }}</p>
                <p>Category: {{ person.category }}</p>
                <p>Contact number: {{ person.phone }}</p>
            {% endif %}
        {% endfor %}
        <a href="{% url 'profile_update' user.id %}" class="btn btn-info btn-sm">Edit Profile</a>

  </div>
{% endblock %}